version: '2'

services:
  application:
    image: debian
    volumes:
      - ./:/var/www/app
  node:
    image: dung13890/client-env
    restart: always
    environment:
      - NODE_ENV=development
    volumes_from:
      - application
    tty: true
